run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - ineffassign
    - misspell
    - errcheck
    - gosimple
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unused
