name: CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

# 设置工作流权限
permissions:
  contents: read
  packages: read

jobs:
  test:
    name: Test
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: windows-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          windows-go-

    - name: Install build dependencies
      run: |
        choco install mingw -y

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: |
        go test -v -race -coverprofile="coverage.txt" -covermode=atomic ./...
      env:
        CGO_ENABLED: 1

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-windows-go1.21

  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck -checks="all,-ST1000" ./...
      env:
        CGO_ENABLED: 1

  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            binary-name: code-outline-windows-amd64.exe
            build-deps: choco install mingw -y
          - os: ubuntu-latest
            binary-name: code-outline-linux-amd64
            build-deps: sudo apt-get update && sudo apt-get install -y build-essential
          - os: macos-latest
            binary-name: code-outline-darwin-amd64
            build-deps: brew install gcc || true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install build dependencies
      run: ${{ matrix.build-deps }}

    - name: Build
      run: |
        mkdir -p build
        go build -v -o build/${{ matrix.binary-name }} ./cmd/code-outline
      env:
        CGO_ENABLED: 1

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: code-outline-${{ matrix.os }}
        path: build/${{ matrix.binary-name }}
